config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root 'blog#index'
  get 'blogs' => 'blog#index', as: 'blogs'
  get 'blogs/new' => 'blog#new', as: 'new_blog'
  get 'blogs/:id' => 'blog#show', as: 'blog'
  post 'blogs' => 'blog#create'
  get 'blog/edit/:id' => 'blog#edit', as: 'edit_blog'
  patch 'blogs/:id' => 'blog#update' 
  delete 'blogs/:id' => 'blog#destroy', as: 'delete_blog'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/blog.rb
class Blog < ApplicationRecord
    validates :title, :content, presence: true
    validates :title, length: { minimum: 10 }
    validates :title, uniqueness: true 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/blog_controller.rb
class BlogController < ApplicationController
    
    def index
        @blogs = Blog.all.sort
    end

    def new
        @blog = Blog.new
    end

    def show
        @blog = Blog.find(params[:id])
    end

    def create
        @blog = Blog.create(blog_params)
        if @blog.valid? 
            redirect_to blogs_path
        else
            redirect_to new_blog_path 
        end
    end
    
    def edit
        @blog = Blog.find(params[:id])
    end

    def update

        @blog = Blog.find(params[:id])
        @blog.update(blog_params)
        if @blog.valid?
            redirect_to blogs_path(@blog)
        else
            redirect_to new_blog_path(@blog)
        end
    end

    def destroy
        @blog = Blog.find(params[:id])
        if @blog.destroy
            redirect_to blogs_path  
        end
    end

private

    def blog_params
        params.require(:blog).permit(:title, :content)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blog_helper.rb
module BlogHelper
end

app/views/blog/edit.html.erb
<h1>Edit a Blog Post:</h1>
<br>
<br>

<%= form_with model: @blog do |form| %>
    <%= form.label :title %>
    <%= form.text_field :title %>
<br>
<br>
    <%= form.label :content %>
    <%= form.text_field :content %>
<br>
<br>
    <%= form.submit 'Edit Blog Post' %>
    
<% end %>
<br>
<br>
<%= link_to 'Back to Home', blogs_path %>

app/views/blog/index.html.erb
<h1>Traveler Blog:</h1>
<ul>

<% @blogs.map do |value|%>
    <li>
    <%= link_to value.title, blog_path(value) %>
    
<% end %>
<br>
<br>
<br>
<%= link_to 'Add a Blog Post', new_blog_path %>
<br>

</ul>

app/views/blog/new.html.erb
<h1>Add a New Blog Post:</h1>

<%= form_with model: @blog do |form| %>
    <%= form.label :title %>
    <%= form.text_field :title %>
<br>
<br>
    <%= form.label :content %>
    <%= form.text_field :content %>
<br>
<br>
    <%= form.submit 'Create Post' %>
    
<% end %>
<br>
<br>
<%= link_to 'Back to Home', '/blogs' %>

app/views/blog/show.html.erb
<h1>Blog Post:</h1>
<ul>
<p>Title:</p>
<%= @blog.title %>

<p>Content:</p>
<%= @blog.content %>

<br>
<br>

<%= button_to 'Delete Item', delete_blog_path(@blog), method: :delete, form:{data: { 'turbo-confirm': 'This will permanently delete your blog post?'} }%>

<br>
<br>
<%= link_to 'Edit a Blog Post', edit_blog_path(@blog)%>
<br>
<br>

<%= link_to 'Back to Home', blogs_path %>

</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TravelBlogPostChallenge</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>